# 安装 NumPy

pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple

## 创建ndarray

In [3]:
import numpy as np

In [4]:
# 一维

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# 查看维度

arr2.ndim

2

In [7]:
# 查看形状

arr2.shape

(2, 4)

In [11]:
# 查看数据类型

arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int64')

In [12]:
# arrange类似Python中的range

np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# NumPy的数据类型有整型int、浮点型float、复数型complex、布尔型bool

# 通过astype()，变换类型
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int64')

In [14]:
float_arr = arr.astype(np.float64)

float_arr.dtype

dtype('float64')

## NumPy的矢量化运算

In [15]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [17]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# 数组与标量的运算

1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [19]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [20]:
# 广播运算，生成布尔数组

arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [21]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [22]:
# 数组的索引和切片

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[5]

5

In [24]:
arr[5:8]

array([5, 6, 7])

In [25]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [26]:
# 数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。

arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [27]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [28]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [29]:
# 高维数组的索引和切片

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [30]:
# 两种等价方法

arr2d[0][2]

3

In [31]:
arr2d[0, 2]

3

In [32]:
# 切片

arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [33]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [34]:
# 高维数组切片

arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# 一次传入多个切片

arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [37]:
arr2d[1, :2]

array([4, 5])

In [38]:
arr2d[:2, 2]

array([3, 6])

In [39]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [40]:
# 布尔型索引

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [41]:
data

array([[-0.77676252,  0.89218642,  0.51518115,  0.34838501],
       [ 0.47381518, -0.09584721, -1.86297066,  0.3020945 ],
       [ 0.99366183,  1.28526356, -0.72457648, -0.89438098],
       [ 0.3038061 ,  1.52055833,  1.53754306, -0.09154399],
       [-0.31505234,  0.99856445, -1.49921722, -0.11896835],
       [-1.01992769, -0.02881909,  0.68868158, -0.18015843],
       [-0.22035566, -0.33433762,  0.38307449, -1.35726191]])

In [42]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [43]:
# 否定条件

names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [44]:
data[~(names == 'Bob')]

array([[ 0.47381518, -0.09584721, -1.86297066,  0.3020945 ],
       [ 0.99366183,  1.28526356, -0.72457648, -0.89438098],
       [-0.31505234,  0.99856445, -1.49921722, -0.11896835],
       [-1.01992769, -0.02881909,  0.68868158, -0.18015843],
       [-0.22035566, -0.33433762,  0.38307449, -1.35726191]])

In [46]:
# 使用&（和）、|（或）之类的布尔算术运算符

mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [47]:
data[mask]

array([[-0.77676252,  0.89218642,  0.51518115,  0.34838501],
       [ 0.99366183,  1.28526356, -0.72457648, -0.89438098],
       [ 0.3038061 ,  1.52055833,  1.53754306, -0.09154399],
       [-0.31505234,  0.99856445, -1.49921722, -0.11896835]])

In [48]:
# 数组的转置

arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [50]:
# 高维数组的转置

arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [51]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [52]:
# 通用函数 ufunc

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [54]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [55]:
# 二元通用函数

x = np.random.randn(8)
y = np.random.randn(8)

x

array([ 1.17952494,  1.10531066,  0.22197906,  0.61483587,  0.28532105,
        0.80140904,  1.40948231, -0.10691364])

In [56]:
y

array([-0.18974455,  1.11517799,  1.8886781 ,  1.01433444,  0.22510136,
        0.31155263,  0.79996362, -0.09167815])

In [57]:
np.maximum(x, y)

array([ 1.17952494,  1.11517799,  1.8886781 ,  1.01433444,  0.28532105,
        0.80140904,  1.40948231, -0.09167815])

更多的通用函数，可以参考https://www.jianshu.com/p/a380222a3292